### ISSUE TITLE
How to remove polyfill-php80

### ISSUE THREAD

**Issue by wisnubaldas** [kenjis/codeigniter-doctrine#4]
hi i am using this library in php 5.6, Codeigniter 3 environment there is an error in `polyfill-php80` dependency, can this be changed to php version 5.6?

![gambar](https://user-images.githubusercontent.com/10908214/99036055-8b37dd80-25b3-11eb-8c75-896b2c71384a.png)

**Comment by kenjis** [comment]
@wisnubaldas 
See <https://github.com/kenjis/codeigniter-doctrine/blob/master/composer.json#L20-L22>.
I don't require `polyfill-php80`.

Check what requires it.
```
$ composer depends symfony/polyfill-php80
```

**Comment by wisnubaldas** [comment]
I found an error running composer update on the php 7.4 console, which is ridiculous :)
